"""Choose the VH bounds of sar_water_otsu v1.1 on the Sen1Floods11 train split, check them on valid.

The test split, Bolivia and the Indian test chips are never looked at here; they are only used by
fit_water.py after the bounds are frozen. Candidates: v1.0 (VV only), VH alone, VV-or-VH with several
(reject-above, default) pairs for the VH threshold fit, and fixed global thresholds.
Metrics per split: share of chips whose water area is within 20% of the hand label (the event the card
confidence predicts), pooled IoU, and the same two for Indian chips.

    python training/calibration/cache_sen1floods11.py   # once
    python training/calibration/tune_water_vh.py         # writes reports/sar_water_vh_tuning.md
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from cache_sen1floods11 import load_cache  # noqa: E402
from fit_water import ROOT  # noqa: E402

from satclip.instruments import water as W  # noqa: E402
from satclip.instruments.common import drop_small  # noqa: E402


def vh_threshold(vh: np.ndarray, max_w: float, default: float) -> float:
    return W.fit_sar_threshold(np.where(np.isfinite(vh), vh, np.nan), max_w, default)["threshold_db"]


def candidates() -> dict:
    def v10(vv, vh, ok):
        return W.classify_sar_water(vv, ok)[0]

    def vh_only(mw, d):
        return lambda vv, vh, ok: drop_small(ok & (vh < vh_threshold(vh, mw, d)), W.MIN_BLOB_PX)

    def union(mw, d):
        def f(vv, vh, ok):
            fit = W.fit_sar_threshold(np.where(np.isfinite(vv), vv, np.nan))
            return drop_small(ok & ((vv < fit["threshold_db"]) | (vh < vh_threshold(vh, mw, d))), W.MIN_BLOB_PX)
        return f

    def fixed(tvv, tvh):
        return lambda vv, vh, ok: drop_small(ok & ((vv < tvv) | (vh < tvh)), W.MIN_BLOB_PX)

    c = {"v1.0: VV only (split-based fit)": v10, "VH only, fit (-19, -22)": vh_only(-19, -22)}
    for mw, d in [(-20, -23), (-19, -22), (-19, -21), (-18, -22), (-18, -21), (-17, -21)]:
        c[f"VV or VH, VH fit ({mw}, {d})"] = union(mw, d)
    c["VV or VH, fixed -15.5 / -22"] = fixed(-15.5, -22)
    return c


def score(fn, chips) -> dict:
    corr, corr_i, I, U, Ii, Ui = [], [], 0, 0, 0, 0
    for c in chips:
        vv, vh, lab = c["vv"], c["vh"], c["label"]
        ok = np.isfinite(vv) & np.isfinite(vh) & (lab >= 0)
        if ok.mean() < 0.5:
            continue
        w, g = fn(vv, vh, ok) & ok, (lab == 1) & ok
        good = abs(int(w.sum()) - int(g.sum())) <= 0.2 * max(int(g.sum()), 0.05 * int(ok.sum()))
        i, u = int((w & g).sum()), int((w | g).sum())
        corr.append(good)
        I, U = I + i, U + u
        if c["event"] == "India":
            corr_i.append(good)
            Ii, Ui = Ii + i, Ui + u
    return {"n": len(corr), "correct": float(np.mean(corr)), "iou": I / max(U, 1),
            "n_in": len(corr_i), "correct_in": float(np.mean(corr_i)) if corr_i else float("nan"), "iou_in": Ii / max(Ui, 1)}


def main() -> None:
    splits = {s: load_cache(s) for s in ("train", "valid")}
    lines = ["# Tuning the VH rule of sar_water_otsu v1.1", "",
             "Generated by `training/calibration/tune_water_vh.py`. Train split used to choose, valid split to check. "
             "Test, Bolivia and the Indian test chips were not used. Correct = water area within 20% of the hand label.", "",
             "| Rule | Train correct | Train pooled IoU | Train India correct (IoU) | Valid correct | Valid pooled IoU | Valid India correct (IoU) |",
             "|---|---|---|---|---|---|---|"]
    for name, fn in candidates().items():
        t, v = score(fn, splits["train"]), score(fn, splits["valid"])
        lines.append(f"| {name} | {t['correct']:.3f} | {t['iou']:.3f} | {t['correct_in']:.3f} ({t['iou_in']:.3f}) | "
                     f"{v['correct']:.3f} | {v['iou']:.3f} | {v['correct_in']:.3f} ({v['iou_in']:.3f}) |")
        print(lines[-1], flush=True)
    lines += ["", f"Chips: train {t['n']} ({t['n_in']} Indian), valid {v['n']} ({v['n_in']} Indian).", "",
              "Chosen: VV or VH with the VH fit rejected above -18 dB and defaulting to -22 dB (gamma0), the best train "
              "share correct with near-best pooled IoU. On valid its share correct is a little below v1.0 (0.42 against 0.45) "
              "while pooled IoU rises (0.51 against 0.43); the margin is small, so the choice was frozen and judged on the "
              "untouched test split in fit_water.py (see sar_water_otsu.md). "
              "Thresholds alone leave Indian chips weak: their labelled water has a median VV near -11 dB "
              "(flooded vegetation and shallow water in paddies), which no backscatter threshold separates well.", ""]
    (HERE / "reports" / "sar_water_vh_tuning.md").write_text("\n".join(lines))


if __name__ == "__main__":
    sys.path.insert(0, str(ROOT / "backend"))
    main()
